# Generated by Django 5.0 on 2024-04-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tenfilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.film')),
            ],
        ),
    ]
