# Generated by Django 5.0 on 2024-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('gioithieu', models.TextField()),
                ('theloai', models.CharField(max_length=255)),
                ('hinhanh', models.ImageField(null=True, upload_to='image')),
                ('banner', models.ImageField(null=True, upload_to='banner')),
                ('video', models.FileField(null=True, upload_to='video')),
                ('date', models.DateField()),
                ('tentap', models.CharField(max_length=255)),
            ],
        ),
    ]
