# Generated by Django 5.0 on 2024-04-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_tenfilm'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='theloai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
