# Generated by Django 4.1.7 on 2024-04-05 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ngaychieu',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 1, 14, 42, 402624)),
        ),
    ]
