# Generated by Django 4.1.7 on 2024-04-06 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_film_ngaychieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='ngaychieu',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 9, 57, 983304)),
        ),
    ]
