# Generated by Django 4.1.7 on 2024-04-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_film_ngaychieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='ngaychieu',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tentap',
        ),
        migrations.RemoveField(
            model_name='film',
            name='video',
        ),
    ]
