# Generated by Django 5.0.4 on 2024-04-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_film_ngaychieu_remove_film_tentap_and_more'),
        ('login', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ten',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.userprofile'),
        ),
    ]
