# Generated by Django 5.0.4 on 2024-04-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_comment_email_remove_comment_ten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=12),
            preserve_default=False,
        ),
    ]
