# Generated by Django 5.0.4 on 2024-04-12 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 19, 34, 13, 552376, tzinfo=datetime.timezone.utc)),
        ),
    ]
