# Generated by Django 5.0.4 on 2024-04-12 21:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_comment_created_at'),
        ('login', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 21, 32, 5, 748089, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RateFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 12, 21, 32, 5, 748089, tzinfo=datetime.timezone.utc))),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.film')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile')),
            ],
            options={
                'unique_together': {('film', 'user_profile')},
            },
        ),
    ]
