# Generated by Django 5.0.4 on 2024-04-12 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_comment_created_at_ratefilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 23, 12, 1, 89954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratefilm',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 23, 12, 1, 89954, tzinfo=datetime.timezone.utc)),
        ),
    ]
