# Generated by Django 5.0.4 on 2024-04-14 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_film_follow_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='views',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 12, 45, 34, 490865, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratefilm',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 12, 45, 34, 490865, tzinfo=datetime.timezone.utc)),
        ),
    ]
