# Generated by Django 5.0.4 on 2024-04-14 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_film_views_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 12, 48, 25, 590067, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratefilm',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 12, 48, 25, 591068, tzinfo=datetime.timezone.utc)),
        ),
    ]
