# Generated by Django 4.1.7 on 2024-04-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chedule',
        ),
    ]
