# Generated by Django 4.1.7 on 2024-04-06 03:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_remove_film_ngaychieu_remove_film_tentap_and_more'),
        ('chedule', '0002_delete_chedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='video')),
                ('tentap', models.CharField(max_length=255)),
                ('ngaychieu', models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 15, 31, 410754))),
                ('TenFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.film')),
            ],
        ),
    ]
