# Generated by Django 4.1.7 on 2024-04-06 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapfilm',
            name='thu_trong_tuan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tapfilm',
            name='ngaychieu',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 14, 32, 12, 41601)),
        ),
    ]
