# Generated by Django 5.0.4 on 2024-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0005_remove_tapfilm_thu_trong_tuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapfilm',
            name='ngaychieu',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tapfilm',
            name='video',
            field=models.FileField(upload_to='video'),
        ),
    ]
