# Generated by Django 5.0.4 on 2024-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0006_alter_tapfilm_ngaychieu_alter_tapfilm_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapfilm',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
