# Generated by Django 5.0.4 on 2024-04-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0009_tapfilm_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapfilm',
            name='views',
        ),
    ]
